language: c
sudo: true
dist: xenial

env:
  global:
    - NAME: five
    - ASDF_SYSTEM: bodge-five
    - DEB_CACHE_DIR: $HOME/.cache/deb/
    - BOOST_CACHE_DIR: $HOME/.cache/boost-dist/
    - BOOST_NAME: boost_1_68_0
    - PATH: ~/bin/:$PATH
    - secure: "qXzqWRgS8wMyjAFA9xwcfHqgBVvDdj1nwI5QWgeF7fnYRf5k32JbWD02/orw2cIsOCk0SavmhlUe/rG1IGOdApjcMVQwS982vFyu5ch7+CSXUFSt97zLga2zzGPrl0j8LYDFoiymQpuphtL3XGaIIJcpw/jS9NzdCiMSrSrLe9S6a71BIGO73aRvgbGepZGMnfSIaIAJqjSFnlPS1wtJdB2uggTEV6dhHibxoqz/nZJlHuipjgT8e1FkIh6w3vMkXplizU7uKCFE5bhdDjvDozU0jPKGtixwUsawR1hxCgUiDHfFazUPUcCgr9BBZzd7Ti/I8iEYkqft9+EQQKXFyiedojpkRlNtqexgxaRAV0nuyH4ZOK1RrdyMGRE2QiSvgGAKzbY2leA7qlVg+yc5bd0W0AP+c5COjUI7poPbi9b/T/Y4EXj8RfVY5MU++nyuYE523HC3y/R/hhXablniLa3jhoTd7pp28JyifVYhZYK6oL7hcIlIlU+58vWNDiX43Ncmk46/la30atK9d+16bUL0sT4vr2hzfZEsF++NH0jIhke+nsOm4qFlPOML2UnXRdRIZ5vWePWCxs9INE0v589T8vsyTG36KG2HzbTPN8UFE5gCGHWU6+Nj6Ntl4fQyfs8tT49oqip6TneV+sjO660UDDr1w0tD1gjuPGJXuyY="

matrix:
  include:
  - os: linux
    env:
      - TARGET_ARCH=x86_64
      - CFLAGS=-m64
      - EXTENSION=so
  - os: osx
    env:
      - TARGET_ARCH=x86_64
      - CFLAGS=-m64
      - EXTENSION=dylib
      - BODGE_CMAKE_FLAGS="-DCMAKE_C_COMPILER=$(which gcc) -DCMAKE_CXX_COMPILER=$(which g++)"

compiler: gcc

branches:
  only:
  - "/^v\\d+(\\.\\d+)+$/"

cache:
  apt: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - $DEB_CACHE_DIR
    - $BOOST_CACHE_DIR

before_install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      mkdir -p $DEB_CACHE_DIR
      mkdir -p $BOOST_CACHE_DIR
      sudo cp -R $DEB_CACHE_DIR/*.deb /var/cache/apt/archives/
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
      sudo apt-get update -q;

      sudo update-alternatives --remove-all gcc;
      sudo update-alternatives --remove-all g++;
      sudo -E apt-get -yq --no-install-suggests --no-install-recommends install patchelf         \
        gcc-8 g++-8 g++-8-multilib libtool-bin autoconf automake libeigen3-dev libpng-dev
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 10;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 10;
      sudo update-alternatives --set gcc /usr/bin/gcc-8;
      sudo update-alternatives --set g++ /usr/bin/g++-8;
      cp -R /var/cache/apt/archives/*.deb $DEB_CACHE_DIR;

      if [ ! -f $BOOST_CACHE_DIR/$BOOST_NAME.tar.bz2 ]; then
        curl -L https://dl.bintray.com/boostorg/release/1.68.0/source/$BOOST_NAME.tar.bz2          \
          -o $BOOST_CACHE_DIR/$BOOST_NAME.tar.bz2                                                  \
        && cd $BOOST_CACHE_DIR                                                                     \
        && tar --bzip2 -xf $BOOST_NAME.tar.bz2                                                     \
        && cd $BOOST_NAME && ./bootstrap.sh && ./b2;
      fi;
      cd $BOOST_CACHE_DIR/$BOOST_NAME && sudo ./b2 install;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       brew update
       brew install libtool eigen boost gcc@8;
       brew link --overwrite --force gcc;
       echo | gcc -xc -E -v -;
       echo | gcc -xc++ -E -v -;
    fi

install:
  - curl -L http://bodge.borodust.org/files/install.sh | sh
  - ln -s $TRAVIS_BUILD_DIR/ ~/quicklisp/local-projects/$ASDF_SYSTEM

script:
  - cd $TRAVIS_BUILD_DIR/lib/ && make clean build
  - rm -rf $TRAVIS_BUILD_DIR/spec/*
  - lisp "$TRAVIS_BUILD_DIR/util/regen-spec.lisp" "$ASDF_SYSTEM" t $TARGET_ARCH
  - cd $TRAVIS_BUILD_DIR/ && zip -r spec.zip spec/

before_deploy:
  - export TARGET_FILE=$TRAVIS_BUILD_DIR/lib$NAME.$EXTENSION.bodged-$TARGET_ARCH-$TRAVIS_OS_NAME-$TRAVIS_BRANCH
  - export TARGET_WRAPPER=$TRAVIS_BUILD_DIR/lib$NAME.$EXTENSION.bodged.wrapper-$TARGET_ARCH-$TRAVIS_OS_NAME-$TRAVIS_BRANCH
  - export SPEC_ARCHIVE=$TARGET_FILE-spec.zip
  - mv $TRAVIS_BUILD_DIR/lib/lib$NAME.$EXTENSION.bodged $TARGET_FILE
  - mv $TRAVIS_BUILD_DIR/lib/lib$NAME.$EXTENSION.bodged.wrapper $TARGET_WRAPPER
  - mv $TRAVIS_BUILD_DIR/spec.zip $SPEC_ARCHIVE

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: [$TARGET_FILE, $SPEC_ARCHIVE, $TARGET_WRAPPER]
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
